var timeout=30;var jNum=8;function AddHistory(){var Str,ShowStr,iArr,TemStr,sArr,jArr;Str=getCookie("history");if(Str==null){Str='';}
if(typeof(play_vid)!="undefined"){if(playtit==''){playtit="继续播放";}
TemStr=play_vid+'$'+infotit+'$'+playtit+'$'+infourl+'$'+window.location.href+'$$';if(Str!=""||Str!="History="){iArr=Str.replace("History=","").split("$$");var n=0
for(var i=0;i<iArr.length-1;i++){if(play_vid-iArr[i].split("$")[0]!=0&&n<jNum-1){TemStr+=iArr[i]+'$$';n++;}}}
TemStr="History="+TemStr
setCookie("history",TemStr,timeout);}}
function WriteHistory(){ShowStr=getCookie("history");if(ShowStr=="History="||ShowStr==null){ShowStr='<li class="kong">没有观看历史</li>';}else{sArr=ShowStr.split("$$");ShowStr='';var curl=window.location.href.split('/')[4];var tg='target="_blank"';if(!isNaN(curl))tg='target="_self"';for(var i=0;i<sArr.length-1;i++){jArr=sArr[i].split("$");jArr1=sArr[i].split("$");if(jArr[1].length>13){jArr1[1]=jArr1[1].substring(0,10)+".."}
if(jArr[2].length>8){jArr1[2]=jArr1[2].substring(0,8)+".."}
ShowStr+='<li><p><a class="del" href="javascript:void(0);" onclick="DelHistory('+i+'); return false;" target="_self" title="删除">\u5220\u9664</a><a href="'+jArr[3]+'" class="name" title="'+jArr[1]+'" target="_blank">'+jArr1[1]+'</a><a href="'+jArr[4]+'" class="his_part" title="继续播放" '+tg+'>['+jArr1[2]+']</a></p></li>';}}
document.getElementById("history").innerHTML=ShowStr;}
function DelHistory(i){var Str,iArr,TemStr,sArr,jArr,ShowStr;TemStr='';Str=getCookie("history");if(Str!=null){if(i==-1){if(confirm("确定清空吗？")){document.getElementById("history").innerHTML='<li class="kong">没有观看历史</li>';setCookie("history","History=");}}else{iArr=Str.replace("History=","").split("$$");for(var j=0;j<iArr.length-1;j++){if(j!=i){TemStr+=iArr[j]+'$$';}}
ShowStr='';sArr=TemStr.split("$$");for(var h=0;h<sArr.length-1;h++){jArr=sArr[h].split("$");jArr1=sArr[h].split("$");if(jArr[1].length>13){jArr1[1]=jArr1[1].substring(0,10)+".."}
if(jArr[2].length>8){jArr1[2]=jArr1[2].substring(0,8)+".."}
ShowStr+='<li><p><a class="del" href="javascript:void(0);" onclick="DelHistory('+h+'); return false;" target="_self" title="删除">\u5220\u9664</a><a href="'+jArr[3]+'" class="name" title="'+jArr[1]+'" target="_blank">'+jArr1[1]+'</a><a href="'+jArr[4]+'" class="his_part" title="继续播放" target="_blank">['+jArr1[2]+']</a></p></li>';}
document.getElementById("history").innerHTML=ShowStr;TemStr="History="+TemStr;setCookie("history",TemStr,timeout);}}}
function add_zero(temp){if(temp<10){return "0"+temp;}else{return temp;}}
function showTop()
{document.getElementById("Tab_top_0").className="history";document.getElementById("List_top_0").style.display="";}
function hideTop()
{var CurTabObj=document.getElementById("Tab_top_0");var CurListObj=document.getElementById("List_top_0");CurTabObj.className="history";CurListObj.style.display="none";}
function switchTab(identify,index,count,cnon,cnout){try{for(i=1;i<count+1;i++){var CurTabObj=document.getElementById("Tab_"+identify+"_"+i);var CurListObj=document.getElementById("List_"+identify+"_"+i);if(i!=index){CurTabObj.className=cnout;CurListObj.style.display="none";}}
document.getElementById("Tab_"+identify+"_"+index).className=cnon;document.getElementById("List_"+identify+"_"+index).style.display="block";jQuery("img").lazyload({container:jQuery("#List_"+identify+"_"+index)});}catch(ee){}}
function playlistTab(identify,index,count,cnon,cnout){try{for(i=1;i<count+1;i++){var CurTabObj=document.getElementById("Tab_"+identify+"_"+i);var CurListObj=document.getElementById("List_"+identify+"_"+i);var CurinfoObj=document.getElementById("info_"+identify+"_"+i);if(i==index){CurTabObj.className=cnon;CurListObj.style.display="block";CurinfoObj.style.display="block";}else{CurTabObj.className=cnout;CurListObj.style.display="none";CurinfoObj.style.display="none";}}}catch(ee){}}
function tab_show(a,b,c,d){x=a,max_i=b,tn=c,tc=d;for(var i=1;i<=max_i;i++){if(document.getElementById(tn+i))document.getElementById(tn+i).className=document.getElementById(tc+i).className="";}
document.getElementById(tn+x).className=document.getElementById(tc+x).className="on";}
function addFavorite(sURL,sTitle){try{window.external.addFavorite(sURL,sTitle);}
catch(e){try{window.sidebar.addPanel(sTitle,sURL,"");}
catch(e)
{alert("加入收藏失败，请使用Ctrl+D进行添加");}}}
function setHome(obj,vrl,url){try{obj.style.behavior='url(#default#homepage)';obj.setHomePage(vrl);this.style.behavior='url(#default#homepage)';this.setHomePage(url);}
catch(e){if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");}
catch(e){alert("此操作被浏览器拒绝！请手动设置");}
var prefs=Components.classes['@mozilla.org/preferences-service;1'].getService(Components.interfaces.nsIPrefBranch);prefs.setCharPref('browser.startup.homepage',vrl);}}}
function dysearch11(){if($("searchword").value=='输入影片名称或演员名'||jQuery("#searchword").val()==""){$("dykw").disabled=='disabled';}else{$("dykw").disabled=='';}
return false;}
function dysearch(){if(jQuery("#searchword").val()=='输入影片名称或演员名'||jQuery("#searchword").val()==''||jQuery.trim(jQuery("#searchword").val())==''){jQuery("#searchword").val('');jQuery("#searchword").focus();return false;}}
function btsearch(){if(jQuery("#searchword1").val()=='输入影片名称或演员名'||jQuery("#searchword1").val()==''||jQuery.trim(jQuery("#searchword").val())==''){jQuery("#searchword1").val('');jQuery("#searchword1").focus();return false;}}
function DelayToSearch(){}
function getsearch(){if(jQuery.trim(jQuery("#searchword").val())){jQuery.getJSON('/json-'+encodeURIComponent(jQuery("#searchword").val()).replace(/%/g,'$')+".html",function(json){if(json.length==0){jQuery(".showresult").html("<em>\u6CA1\u6709\u627E\u5230\u4EFB\u4F55\u5F71\u7247\uFF0C\u8BF7\u5C1D\u8BD5\u4FEE\u6539\u5173\u952E\u8BCD</em>");}else{var tmpstr="";jQuery.each(json,function(i,obj){tmpstr+="<li><a target=\"_blank\" href=\""+obj.url+"\"><label>"+obj.tyname+"</label><p>"+obj.title.replace(jQuery("#searchword").val(),"<span>"+jQuery("#searchword").val()+"</span>")+"</p></a></li>";});jQuery(".showresult").html(tmpstr);}
jQuery(".showresult").slideDown();});}else{jQuery(".showresult").html("");jQuery(".showresult").slideUp();}}
function endfun(){jQuery("#searchword").focus(function(){if(jQuery(".showresult").html())jQuery(".showresult").slideDown();});jQuery("#searchword").blur(function(){jQuery(".showresult").delay(200).slideUp();});jQuery("#dykw").val(' ');}
function killErrors(){return true;}
function __yx_SetMainPlayIFrameSRC(_in_id,cb_getplay_url){return __getset_play(_in_id,cb_getplay_url,3)}function __ipchk_getplay(_in_data){const match_resl=_in_data.match(/^ipchk:(.+)/);if(match_resl){$("#ipchk_getplay").html(_in_data);$("#ipchk_getplay").removeAttr("hidden");return true}return false}function __getset_play(_in_id,cb_getplay_url,cb_cnt){const _url=window.location.href;const _rand=Math.random();const _getplay_url=cb_getplay_url();$.get(_getplay_url,function(_in_data,_in_status){if(__ipchk_getplay(_in_data)){return false}const _json_obj=JSON.parse(_in_data);const _purl=_json_obj["purl"];const _vurl=_json_obj["vurl"];const _play_ex=_json_obj["ex"];const vlt_lr=__get_vlt_lr(_play_ex);const _playid=_json_obj["playid"];var _vurlp2_getplay_url="";document.getElementById(_in_id).src=___make_url_vlt_param(_purl+_vurl+_vurlp2_getplay_url,vlt_lr);return true});return false}function __get_vlt_lr(_in_ex){const re_resl=_in_ex.match(/^#ex=.+#vlt=L(\d+)R(\d+)/);var vlt_lr=[0,0];if(re_resl){vlt_lr=[__key_enc_vlt(re_resl[1]),__key_enc_vlt(re_resl[2])]}return vlt_lr}function ___make_url_vlt_param(_in_url,vlt_lr){var xxx=(_in_url.indexOf("?")>0?"&":"?");_in_url+=(xxx+"vlt_l="+vlt_lr[0]+"&vlt_r="+vlt_lr[1]);return _in_url}function __cb_getplay_url(){const _url=window.location.href;const _rand=Math.random();const _getplay_url=(_url.replace(/.*\/player\/(\d+?)-(\d+?)-(\d+?)\.html.*/,"/_getplay?aid=$1&playindex=$2&epindex=$3")+"&r="+_rand);return _getplay_url}const __yh_g_exXP=[""];var __yh_g_isfullscn=false;var __yh_g_new_playleft_id=null;var __yh_margin_bak="";function __yh_playfull_set(_in_id,_in_title_on,_in_exXP){if(!navigator.userAgent.match(/(iPhone|iPod|Android|mobile|blackberry|webos|incognito|webmate|bada|nokia|lg|ucweb|skyfire)/i)){$("#"+_in_id).append('<a class="fullscn'+_in_exXP+'">'+_in_title_on+"</a>");if(!__yh_g_isfullscn||!_in_exXP){$((".fullscn"+_in_exXP)).show()}$("#"+_in_id).mouseover(function(){if(!__yh_g_isfullscn||!_in_exXP){$((".fullscn"+_in_exXP)).show()}}).mouseout(function(){$((".fullscn"+_in_exXP)).hide()});$((".fullscn"+_in_exXP)).click(function(){if(!__yh_g_isfullscn){$((".fullscn"+"")).html("还原窗口");const _new_ID=("fullplayleft"+_in_exXP);$("#"+_in_id+" iframe").css("width","100%");$("#"+_in_id+" iframe").css("height","100%");__yh_margin_bak=$("#"+_in_id+" iframe").css("margin");$("#"+_in_id+" iframe").css("margin","0px");$("#"+_in_id).attr("id",_new_ID);__yh_g_new_playleft_id=_new_ID;__yh_g_isfullscn=true}else{$((".fullscn"+"")).html(_in_title_on);$("#"+_in_id+" iframe").css("margin",__yh_margin_bak);$(("#"+__yh_g_new_playleft_id)).attr("id",_in_id);__yh_g_isfullscn=false}})}}function __yh_exp_playfull_set(_in_id){for(var i=0;i<__yh_g_exXP.length;i++){const p1=(__yh_g_exXP[i]?("网页"+__yh_g_exXP[i]+"P"):"网页全屏");const p2=(__yh_g_exXP[i]?("-"+__yh_g_exXP[i]+"p"):"");__yh_playfull_set(_in_id,p1,p2)}};
window.onerror=killErrors;
